package com.generator.mapper;

import com.generator.pojo.Blogcategory;
import com.generator.pojo.BlogcategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int countByExample(BlogcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int deleteByExample(BlogcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int insert(Blogcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int insertSelective(Blogcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    List<Blogcategory> selectByExample(BlogcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    Blogcategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Blogcategory record, @Param("example") BlogcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Blogcategory record, @Param("example") BlogcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Blogcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogcategory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Blogcategory record);
}