package com.generator.pojo;

public class Blogcategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.categoryName
     *
     * @mbggenerated
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.categoryNum
     *
     * @mbggenerated
     */
    private Integer categorynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogcategory.categoryOrderNo
     *
     * @mbggenerated
     */
    private Integer categoryorderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.id
     *
     * @return the value of blogcategory.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.id
     *
     * @param id the value for blogcategory.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.categoryName
     *
     * @return the value of blogcategory.categoryName
     *
     * @mbggenerated
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.categoryName
     *
     * @param categoryname the value for blogcategory.categoryName
     *
     * @mbggenerated
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.categoryNum
     *
     * @return the value of blogcategory.categoryNum
     *
     * @mbggenerated
     */
    public Integer getCategorynum() {
        return categorynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.categoryNum
     *
     * @param categorynum the value for blogcategory.categoryNum
     *
     * @mbggenerated
     */
    public void setCategorynum(Integer categorynum) {
        this.categorynum = categorynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogcategory.categoryOrderNo
     *
     * @return the value of blogcategory.categoryOrderNo
     *
     * @mbggenerated
     */
    public Integer getCategoryorderno() {
        return categoryorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogcategory.categoryOrderNo
     *
     * @param categoryorderno the value for blogcategory.categoryOrderNo
     *
     * @mbggenerated
     */
    public void setCategoryorderno(Integer categoryorderno) {
        this.categoryorderno = categoryorderno;
    }
}