package com.generator.pojo;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.clickhit
     *
     * @mbggenerated
     */
    private Integer clickhit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blognum
     *
     * @mbggenerated
     */
    private Integer blognum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogimg
     *
     * @mbggenerated
     */
    private String blogimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogOrderNo
     *
     * @mbggenerated
     */
    private Integer blogorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogCategoryId
     *
     * @mbggenerated
     */
    private Integer blogcategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.summary
     *
     * @return the value of blog.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.summary
     *
     * @param summary the value for blog.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.clickhit
     *
     * @return the value of blog.clickhit
     *
     * @mbggenerated
     */
    public Integer getClickhit() {
        return clickhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.clickhit
     *
     * @param clickhit the value for blog.clickhit
     *
     * @mbggenerated
     */
    public void setClickhit(Integer clickhit) {
        this.clickhit = clickhit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blognum
     *
     * @return the value of blog.blognum
     *
     * @mbggenerated
     */
    public Integer getBlognum() {
        return blognum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blognum
     *
     * @param blognum the value for blog.blognum
     *
     * @mbggenerated
     */
    public void setBlognum(Integer blognum) {
        this.blognum = blognum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogimg
     *
     * @return the value of blog.blogimg
     *
     * @mbggenerated
     */
    public String getBlogimg() {
        return blogimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogimg
     *
     * @param blogimg the value for blog.blogimg
     *
     * @mbggenerated
     */
    public void setBlogimg(String blogimg) {
        this.blogimg = blogimg == null ? null : blogimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogOrderNo
     *
     * @return the value of blog.blogOrderNo
     *
     * @mbggenerated
     */
    public Integer getBlogorderno() {
        return blogorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogOrderNo
     *
     * @param blogorderno the value for blog.blogOrderNo
     *
     * @mbggenerated
     */
    public void setBlogorderno(Integer blogorderno) {
        this.blogorderno = blogorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogCategoryId
     *
     * @return the value of blog.blogCategoryId
     *
     * @mbggenerated
     */
    public Integer getBlogcategoryid() {
        return blogcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogCategoryId
     *
     * @param blogcategoryid the value for blog.blogCategoryId
     *
     * @mbggenerated
     */
    public void setBlogcategoryid(Integer blogcategoryid) {
        this.blogcategoryid = blogcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.date
     *
     * @return the value of blog.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.date
     *
     * @param date the value for blog.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}