package com.generator.pojo;

public class Link {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.linkName
     *
     * @mbggenerated
     */
    private String linkname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.linkURL
     *
     * @mbggenerated
     */
    private String linkurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.orderNo
     *
     * @mbggenerated
     */
    private Integer orderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.linkName
     *
     * @return the value of link.linkName
     *
     * @mbggenerated
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.linkName
     *
     * @param linkname the value for link.linkName
     *
     * @mbggenerated
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname == null ? null : linkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.linkURL
     *
     * @return the value of link.linkURL
     *
     * @mbggenerated
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.linkURL
     *
     * @param linkurl the value for link.linkURL
     *
     * @mbggenerated
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl == null ? null : linkurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.orderNo
     *
     * @return the value of link.orderNo
     *
     * @mbggenerated
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.orderNo
     *
     * @param orderno the value for link.orderNo
     *
     * @mbggenerated
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }
}